Repository vitejs/vite-plugin-vue, pull requests merged in 2023-08, with the labels that each got.

#223 fix: make it work when a default lang was specified
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/script.ts
  packages/plugin-vue/src/template.ts
  playground/vue/DefaultLangs.vue
  playground/vue/Main.vue
  playground/vue/__tests__/vue.spec.ts
  playground/vue/tsconfig.json
Labels: p3-minor-bug :hammer:

#224 test: migrate tailwind + pug test from Vite repo
  playground/tailwind/App.vue
  playground/tailwind/PugTemplate.vue
  playground/tailwind/__tests__/tailwind.spec.ts
  playground/tailwind/index.css
  playground/tailwind/index.html
  playground/tailwind/package.json
  playground/tailwind/postcss.config.ts
  playground/tailwind/tailwind.config.js
  playground/tailwind/vite.config.ts
  pnpm-lock.yaml
Labels: p1-chore :broom:

#221 docs: add example for transforming custom blocks
  packages/plugin-vue/README.md
Labels: documentation

#183 chore: cleanup hoist patterns
  .npmrc
Labels: p1-chore :broom:
