Repository vitejs/vite-plugin-vue, pull requests merged in 2024-11, with the labels that each got.

#446 fix(hmr): re-resolve script after type dep changed
  packages/plugin-vue/src/index.ts
  playground/vue/Main.vue
  playground/vue/TypePropsTsx.vue
  playground/vue/__tests__/vue.spec.ts
Labels: feat: hmr, ready to merge

#471 fix(hmr): should reload if relies file changed after re-render
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/src/main.ts
  playground/vue/Hmr.vue
  playground/vue/__tests__/vue.spec.ts
  playground/vue/lib.js
Labels: feat: hmr

#380 fix: explicitly export ssrRegisterHelper as const in plugin-vue-jsx (fix #376)
  packages/plugin-vue-jsx/src/index.ts
Labels: feat: ssr, p1-chore :broom:, ready to merge

#481 chore: add vite 6 peer dep
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue/package.json
  playground/vue-legacy/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: p1-chore :broom:
