Repository vitejs/vite-plugin-vue, pull requests merged in 2025-03, with the labels that each got.

#541 fix(plugin-vue): ensure HMR updates styles when SFC is treated as a type dependency
  packages/plugin-vue/src/handleHotUpdate.ts
  packages/plugin-vue/src/index.ts
  playground/vue/ExportTypeProps1.vue
  playground/vue/ExportTypeProps2.vue
  playground/vue/Main.vue
  playground/vue/__tests__/vue.spec.ts
Labels: p3-minor-bug :hammer:, ready to merge

#533 feat(css): tree shake scoped styles
  packages/plugin-vue/src/index.ts
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/style.ts
  packages/plugin-vue/src/utils/descriptorCache.ts
  playground/ssr-vue/vite.config.js
  playground/vue/Main.vue
  playground/vue/TreeShakeScopedStyle.vue
  playground/vue/__tests__/vue.spec.ts
Labels: p2-nice-to-have :cake:

#552 ci: pin commit for actions
  .github/renovate.json5
Labels: p1-chore :broom:

#559 chore: fix types with Vite 6.3
  packages/plugin-vue/src/style.ts
Labels: p1-chore :broom:
