Repository vitejs/vite-plugin-vue, pull requests merged in 2025-05, with the labels that each got.

#583 chore: use rollup types exposed from Vite
  packages/plugin-vue/src/main.ts
  packages/plugin-vue/src/style.ts
  packages/plugin-vue/src/template.ts
  packages/plugin-vue/src/utils/error.ts
  playground/vitestSetup.ts
  playground/vue-lib/__tests__/vue-lib.spec.ts
Labels: p1-chore :broom:

#585 fix(plugin-vue): handle sourcemap with empty script code
  packages/plugin-vue/src/main.ts
  playground/vue-sourcemap/EmptyScript.vue
  playground/vue-sourcemap/__tests__/__snapshots__/vue-sourcemap.spec.ts.snap
  playground/vue-sourcemap/__tests__/vue-sourcemap.spec.ts
Labels: p3-minor-bug :hammer:

#584 feat(plugin-vue): use `transformWithOxc` if `rolldown-vite` is detected
  packages/plugin-vue/src/main.ts
Labels: p3-significant 🔨

#581 feat(vue-jsx): add filter
  packages/plugin-vue-jsx/package.json
  packages/plugin-vue-jsx/src/index.ts
  pnpm-lock.yaml
Labels: p3-significant 🔨

#582 feat(vue)!: separate include and exclude from `api.options` and add filter
  packages/plugin-vue/package.json
  packages/plugin-vue/src/index.ts
  pnpm-lock.yaml
Labels: p3-significant 🔨
